
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame  {
    static DateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
    static int madre = 1;
    static int padre = 1;
    static int hermano = 1;
    static int hermana = 4;
    static int esposo = 1;
    static ArrayList<Persona> lista = new ArrayList();
    static ArrayList<Objeto> lista2 = new ArrayList();

    public Principal() {
        initComponents();
        String usuarioadmin = "kim";
        String contraadmin = "abc123";
        tab.setEnabledAt(4, false);
        tab.setEnabledAt(3, false);
        tab.setEnabledAt(2, false);
        tab.setEnabledAt(1, false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_sexos = new javax.swing.ButtonGroup();
        bg_estado = new javax.swing.ButtonGroup();
        bg_rol = new javax.swing.ButtonGroup();
        bg_calidad = new javax.swing.ButtonGroup();
        bg_tipo = new javax.swing.ButtonGroup();
        jLabel31 = new javax.swing.JLabel();
        tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_contra = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        spinner_edad = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rb_m = new javax.swing.JRadioButton();
        rb_f = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rb_soltero = new javax.swing.JRadioButton();
        rb_casado = new javax.swing.JRadioButton();
        rb_otro = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        rb_madre = new javax.swing.JRadioButton();
        rb_padre = new javax.swing.JRadioButton();
        rb_hermana = new javax.swing.JRadioButton();
        rb_hermano = new javax.swing.JRadioButton();
        rb_esposo = new javax.swing.JRadioButton();
        b_agregar = new javax.swing.JButton();
        b_modificar = new javax.swing.JButton();
        b_eliminar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tf_trabajo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_altura = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_peso = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tf_contraf = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tf_nombrep = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        spinner_edadp = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        tf_idp = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        rb_mp = new javax.swing.JRadioButton();
        rb_fp = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        rb_solterop = new javax.swing.JRadioButton();
        rb_casadop = new javax.swing.JRadioButton();
        rb_otrop = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        tf_ocupacion = new javax.swing.JTextField();
        tf_horario = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tf_tiempo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tf_sueldo = new javax.swing.JTextField();
        b_agregarp = new javax.swing.JButton();
        b_modificarp = new javax.swing.JButton();
        b_eliminarp = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        tf_contrap = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        tf_color = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descripcion = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        tf_marca = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tf_tam = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        rb_1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        rb7 = new javax.swing.JRadioButton();
        rb8 = new javax.swing.JRadioButton();
        rb9 = new javax.swing.JRadioButton();
        rb10 = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        tf_precio = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        rb_zapatos = new javax.swing.JRadioButton();
        rb_ropa = new javax.swing.JRadioButton();
        rb_objetos = new javax.swing.JRadioButton();
        b_agregarobjeto = new javax.swing.JButton();
        b_modificaro = new javax.swing.JButton();
        b_eliminarobjetos = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();

        jLabel31.setText("jLabel31");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Iniciar Sesion");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Cerrar Sesion");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("para iniciar sesion como admin, usuario: kim; password: abc123");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_usuario)
                            .addComponent(tf_contra, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(187, 187, 187)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabel21)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        tab.addTab("Login", jPanel1);

        jLabel3.setText("Nombre");

        spinner_edad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setText("Edad");

        jLabel5.setText("ID");

        jLabel6.setText("Sexo");

        bg_sexos.add(rb_m);
        rb_m.setSelected(true);
        rb_m.setText("Masculino");

        bg_sexos.add(rb_f);
        rb_f.setText("Femenino");

        jLabel7.setText("Estado civil");

        bg_estado.add(rb_soltero);
        rb_soltero.setSelected(true);
        rb_soltero.setText("Soltero/a");

        bg_estado.add(rb_casado);
        rb_casado.setText("Casado/a");

        bg_estado.add(rb_otro);
        rb_otro.setText("Otro/a");

        jLabel8.setText("Rol");

        bg_rol.add(rb_madre);
        rb_madre.setSelected(true);
        rb_madre.setText("Madre");
        rb_madre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_madreActionPerformed(evt);
            }
        });

        bg_rol.add(rb_padre);
        rb_padre.setText("Padre");

        bg_rol.add(rb_hermana);
        rb_hermana.setText("Hermana");

        bg_rol.add(rb_hermano);
        rb_hermano.setText("Hermano");

        bg_rol.add(rb_esposo);
        rb_esposo.setText("Esposo");

        b_agregar.setText("Agregar");
        b_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_agregarActionPerformed(evt);
            }
        });

        b_modificar.setText("Modificar");
        b_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_modificarMouseClicked(evt);
            }
        });

        b_eliminar.setText("Eliminar");
        b_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_eliminarActionPerformed(evt);
            }
        });

        jLabel9.setText("Trabajo");

        jLabel10.setText("Altura");

        jLabel11.setText("Peso");

        jLabel22.setText("Contraseña");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(rb_soltero)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_casado)
                            .addComponent(rb_padre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_otro)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rb_hermana)
                                .addGap(118, 118, 118)
                                .addComponent(rb_esposo))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(45, 45, 45)
                        .addComponent(rb_madre))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_trabajo)
                            .addComponent(tf_altura)
                            .addComponent(tf_peso, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(b_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(73, 73, 73)
                                    .addComponent(b_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(rb_hermano)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                            .addComponent(b_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(rb_m)
                                    .addGap(46, 46, 46)
                                    .addComponent(rb_f))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_nombre)
                                        .addComponent(tf_id, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                        .addComponent(spinner_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(164, 164, 164)
                                    .addComponent(tf_contraf, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(tf_contraf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinner_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rb_m)
                    .addComponent(rb_f))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rb_soltero)
                    .addComponent(rb_casado)
                    .addComponent(rb_otro))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rb_padre)
                    .addComponent(rb_hermana)
                    .addComponent(rb_hermano)
                    .addComponent(rb_esposo)
                    .addComponent(rb_madre))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab.addTab("Registrar familia", jPanel2);

        jLabel12.setText("Nombre");

        jLabel13.setText("Edad");

        jLabel14.setText("ID");

        jLabel15.setText("Sexo");

        bg_sexos.add(rb_mp);
        rb_mp.setText("Masculino");
        rb_mp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_mpActionPerformed(evt);
            }
        });

        bg_sexos.add(rb_fp);
        rb_fp.setText("Femenino");

        jLabel16.setText("Estado");

        bg_estado.add(rb_solterop);
        rb_solterop.setText("Soltero/a");

        bg_estado.add(rb_casadop);
        rb_casadop.setText("Casado/a");

        bg_estado.add(rb_otrop);
        rb_otrop.setText("Otro/a");

        jLabel17.setText("Ocupacion");

        jLabel18.setText("Horario");

        jLabel19.setText("Tiempo trabajando");

        jLabel20.setText("Sueldo");

        b_agregarp.setText("Agregar");
        b_agregarp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_agregarpMouseClicked(evt);
            }
        });

        b_modificarp.setText("Modificar");
        b_modificarp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_modificarpMouseClicked(evt);
            }
        });

        b_eliminarp.setText("Eliminar");
        b_eliminarp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_eliminarpMouseClicked(evt);
            }
        });

        jLabel23.setText("Contraseña");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rb_solterop)
                                .addGap(18, 18, 18)
                                .addComponent(rb_casadop)
                                .addGap(18, 18, 18)
                                .addComponent(rb_otrop))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rb_mp)
                                .addGap(18, 18, 18)
                                .addComponent(rb_fp))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nombrep)
                                    .addComponent(tf_idp, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(spinner_edadp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(179, 179, 179)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_contrap, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_horario, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(tf_ocupacion)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(tf_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(b_agregarp, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(b_modificarp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(b_eliminarp, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_nombrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(tf_contrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(spinner_edadp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_idp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(rb_mp)
                    .addComponent(rb_fp))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(rb_solterop)
                    .addComponent(rb_casadop)
                    .addComponent(rb_otrop))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_agregarp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_modificarp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_eliminarp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        tab.addTab("Registrar Personal", jPanel3);

        jLabel24.setText("Color");

        jLabel25.setText("Descripcion");

        ta_descripcion.setColumns(20);
        ta_descripcion.setRows(5);
        jScrollPane1.setViewportView(ta_descripcion);

        jLabel26.setText("Marca");

        jLabel27.setText("Tamaño");

        jLabel28.setText("calidad");

        bg_calidad.add(rb_1);
        rb_1.setSelected(true);
        rb_1.setText("1");

        bg_calidad.add(rb2);
        rb2.setText("2");

        bg_calidad.add(rb3);
        rb3.setText("3");

        bg_calidad.add(rb4);
        rb4.setText("4");

        bg_calidad.add(rb5);
        rb5.setText("5");

        bg_calidad.add(rb6);
        rb6.setText("6");

        bg_calidad.add(rb7);
        rb7.setText("7");

        bg_calidad.add(rb8);
        rb8.setText("8");

        bg_calidad.add(rb9);
        rb9.setText("9");

        bg_calidad.add(rb10);
        rb10.setText("10");

        jLabel29.setText("Precio");

        jLabel30.setText("Tipo");

        bg_tipo.add(rb_zapatos);
        rb_zapatos.setText("Zapatos");

        bg_tipo.add(rb_ropa);
        rb_ropa.setText("Ropa");

        bg_tipo.add(rb_objetos);
        rb_objetos.setText("Objetos Del Hogar");

        b_agregarobjeto.setText("Agregar");
        b_agregarobjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_agregarobjetoMouseClicked(evt);
            }
        });

        b_modificaro.setText("Modificar objetos");
        b_modificaro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_modificaroMouseClicked(evt);
            }
        });

        b_eliminarobjetos.setText("Eliminar objetos");
        b_eliminarobjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_eliminarobjetosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(tf_color, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tf_tam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                        .addComponent(tf_marca, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(rb_1)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb2)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb3)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb4)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb5)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb6)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb7)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb8)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb9)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb10))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(rb_zapatos)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_ropa)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_objetos)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(b_agregarobjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(b_modificaro, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(b_eliminarobjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_tam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(rb_1)
                    .addComponent(rb2)
                    .addComponent(rb3)
                    .addComponent(rb4)
                    .addComponent(rb5)
                    .addComponent(rb6)
                    .addComponent(rb7)
                    .addComponent(rb8)
                    .addComponent(rb9)
                    .addComponent(rb10))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(rb_zapatos)
                    .addComponent(rb_ropa)
                    .addComponent(rb_objetos))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_agregarobjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_modificaro, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_eliminarobjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        tab.addTab("Agregar objetos", jPanel4);

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla1);

        jButton3.setText("Listar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jButton3)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton3)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        tab.addTab("Ver todas las personas", jPanel5);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vitamin-Ha-kardashian.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel32)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel32)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tab.addTab("Uy", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_mpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_mpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_mpActionPerformed

    private void rb_madreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_madreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_madreActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (tf_usuario.getText().equals("kim") && tf_contra.getText().equals("abc123")) {
            tf_usuario.setText("");
            tf_contra.setText("");
            tab.setEnabledAt(4, true);
            tab.setEnabledAt(3, true);
            tab.setEnabledAt(2, true);
            tab.setEnabledAt(1, true);
        } else {
            for (Persona x : lista) {
                if (x.getNombre().equals(tf_usuario.getText()) && x.getContra().equals(tf_contra.getText())) {
                    JOptionPane.showMessageDialog(this, "Ha ingresado correctamente");
                    tf_usuario.setText("");
                    tf_contra.setText("");

                }
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void b_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_agregarActionPerformed
        try {
            String nombre = tf_nombre.getText();
            String contra = tf_contraf.getText();
            int edad = ((int) spinner_edad.getValue());
            String id = tf_id.getText();
            String sexo;
            if (rb_m.isSelected()) {
                sexo = "Masculino";
            } else {
                sexo = "Femenino";
            }
            String estado = "";
            if (rb_casado.isSelected()) {

                estado = "Casado";
            }
            if (rb_soltero.isSelected()) {
                estado = "soltero";
            }
            if (rb_otro.isSelected()) {
                estado = "otro";
            }
            Objeto objeto = null;
            String rol = "";
            if (rb_padre.isSelected()) {
                if (padre > 0) {
                    rol = "padre";
                    padre--;
                } else {
                    rol = "colado";
                }
            }
            if (rb_madre.isSelected()) {
                if (madre > 0) {
                    rol = "madre";
                    madre--;
                } else {
                    rol = "colado";
                }
            }
            if (rb_hermano.isSelected()) {
                if (hermano > 0) {
                    rol = "hermano";
                    hermano--;
                } else {
                    rol = "colado";
                }
            }
            if (rb_hermana.isSelected()) {
                if (hermana > 0) {
                    rol = "hermana";
                    hermana--;
                } else {
                    rol = "colado";
                }
            }
            if (rb_hermana.isSelected()) {
                if (hermana > 0) {
                    rol = "hermana";
                    hermana--;
                } else {
                    rol = "colado";
                }
            }
            if (rb_esposo.isSelected()) {
                if (esposo > 0) {
                    rol = "esposo";
                    esposo--;
                } else {
                    rol = "colado";
                }
            }
            String trabajo = tf_trabajo.getText();
            double altura = Double.parseDouble(tf_altura.getText());
            double peso = Double.parseDouble(tf_peso.getText());
            lista.add(new Familiar(rol, trabajo, altura, peso, nombre, edad, id, sexo, estado, objeto, contra));
            tf_nombre.setText("");
            tf_contraf.setText("");
            tf_id.setText("");
            tf_trabajo.setText("");
            tf_altura.setText("");
            tf_peso.setText("");
            System.out.println(lista);
            System.out.println("");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "ocurrio un error y no se pudieron agregar los datos");
        }
    }//GEN-LAST:event_b_agregarActionPerformed

    private void b_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_modificarMouseClicked
        System.out.println(lista);
        System.out.println("");
        int pos = Integer.parseInt(JOptionPane.showInputDialog("Ingrese posicion que desea modificar"));
        int opc = Integer.parseInt(JOptionPane.showInputDialog("1.modificar nombre\n" + "2.modificar contraseña\n" + "3.modificar id\n" + "Ingrese numero de lo que desea modificar"));
        while (opc > 3) {
            opc = Integer.parseInt(JOptionPane.showInputDialog("Ingrese una opcion del 1 al 3"));
        }
        if (opc == 1) {
            String n_nombre = JOptionPane.showInputDialog("Ingrese nuevo nombre");
            lista.get(pos).setNombre(n_nombre);
        }
        if (opc == 2) {
            String n_contra = JOptionPane.showInputDialog("Ingrese nueva contraseña");
            lista.get(pos).setContra(n_contra);
        }
        if (opc == 3) {
            String n_id = JOptionPane.showInputDialog("Ingrese nuevo id");
            lista.get(pos).setId(n_id);
        }
        System.out.println(lista);
        System.out.println("");
    }//GEN-LAST:event_b_modificarMouseClicked

    private void b_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_eliminarActionPerformed
        int pos = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la posicion que desea elminiar"));
        System.out.println(lista);
        System.out.println("");
        lista.remove(pos);
    }//GEN-LAST:event_b_eliminarActionPerformed

    private void b_agregarpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_agregarpMouseClicked
        try {
            String nombre = tf_nombrep.getText();
            String contra = tf_contrap.getText();
            int edad = ((int) spinner_edadp.getValue());
            String id = tf_idp.getText();
            String sexo;
            if (rb_mp.isSelected()) {
                sexo = "Masculino";
            } else {
                sexo = "Femenino";
            }
            String estado = "";
            Objeto objeto = null;
            if (rb_casadop.isSelected()) {

                estado = "Casado";
            }
            if (rb_solterop.isSelected()) {
                estado = "soltero";
            }
            if (rb_otrop.isSelected()) {
                estado = "otro";
            }
            String ocupacion = tf_ocupacion.getText();
            String horario = tf_horario.getText();
            String tiempo = tf_tiempo.getText();
            double sueldo = Double.parseDouble(tf_sueldo.getText());
            lista.add(new Personal(ocupacion, horario, tiempo, sueldo, nombre, edad, id, sexo, estado, objeto, contra));
            tf_nombrep.setText("");
            tf_contrap.setText("");
            tf_idp.setText("");
            tf_ocupacion.setText("");
            tf_horario.setText("");
            tf_tiempo.setText("");
            tf_sueldo.setText("");
            System.out.println(lista);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "ocurrio un error y no se pudieron agregar los datos");
        }
    }//GEN-LAST:event_b_agregarpMouseClicked

    private void b_modificarpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_modificarpMouseClicked
        System.out.println(lista);
        int pos = Integer.parseInt(JOptionPane.showInputDialog("Ingrese posicion que desea modificar"));
        int opc = Integer.parseInt(JOptionPane.showInputDialog("1.modificar nombre\n" + "2.modificar contraseña\n" + "3.modificar id\n" + "Ingrese numero de lo que desea modificar"));
        while (opc > 3) {
            opc = Integer.parseInt(JOptionPane.showInputDialog("Ingrese una opcion del 1 al 3"));
        }
        if (opc == 1) {
            String n_nombre = JOptionPane.showInputDialog("Ingrese nuevo nombre");
            lista.get(pos).setNombre(n_nombre);
        }
        if (opc == 2) {
            String n_contra = JOptionPane.showInputDialog("Ingrese nueva contraseña");
            lista.get(pos).setContra(n_contra);
        }
        if (opc == 3) {
            String n_id = JOptionPane.showInputDialog("Ingrese nuevo id");
            lista.get(pos).setId(n_id);
        }
        System.out.println(lista);

    }//GEN-LAST:event_b_modificarpMouseClicked

    private void b_eliminarpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_eliminarpMouseClicked
        int pos = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la posicion que desea elminiar"));
        System.out.println(lista);
        lista.remove(pos);
        System.out.println(lista);
    }//GEN-LAST:event_b_eliminarpMouseClicked

    private void b_agregarobjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_agregarobjetoMouseClicked
        String color = tf_color.getText();
        String descripcion = ta_descripcion.getText();
        String marca = tf_marca.getText();
        String tam = tf_tam.getText();
        String calidad = "";
        if (rb_1.isSelected()) {
            calidad = "1";
        }
        if (rb2.isSelected()) {
            calidad = "2";
        }
        if (rb3.isSelected()) {
            calidad = "3";
        }
        if (rb4.isSelected()) {
            calidad = "4";
        }
        if (rb5.isSelected()) {
            calidad = "5";
        }
        if (rb6.isSelected()) {
            calidad = "6";
        }
        if (rb7.isSelected()) {
            calidad = "7";
        }
        if (rb8.isSelected()) {
            calidad = "8";
        }
        if (rb9.isSelected()) {
            calidad = "9";
        }
        if (rb10.isSelected()) {
            calidad = "10";
        }
        double precio = Double.parseDouble(tf_precio.getText());
        String tipo = "";
        if (rb_zapatos.isSelected()) {
            tipo = "Zapatos";
            String talla = JOptionPane.showInputDialog("Ingrese talla de los zapatos");
            String suela = JOptionPane.showInputDialog("Ingrese material de la suela");
            String confort = JOptionPane.showInputDialog("Ingrese el confort del zapato 1-10");
            int pos = Integer.parseInt(JOptionPane.showInputDialog("Ingrese posicion de la persona dueña del objeto"));
            lista.get(pos).getLista().add(new Zapatos(talla, suela, confort, color, descripcion, marca, tam, calidad, precio, suela, tipo));
            System.out.println(lista);

        }
        if (rb_ropa.isSelected()) {
            tipo = "Ropa";
            String talla=JOptionPane.showInputDialog("Ingrese talla de la ropa");
            String material=JOptionPane.showInputDialog("Ingrese material de la ropa");
            String pais=JOptionPane.showInputDialog("Ingrese pais de donde viene la ropa");
            int pos = Integer.parseInt(JOptionPane.showInputDialog("Ingrese posicion de la persona dueña del objeto"));
            lista.get(pos).getLista().add(new Ropa( talla,  material,  pais, color,  descripcion,  marca,  tam,  calidad,  precio,  lista.get(pos).getNombre(), tipo));
            System.out.println(lista);

        }
        if (rb_objetos.isSelected()) {
            try {
                tipo = "Objetos del hogar";
                String tiempo=JOptionPane.showInputDialog("Ingrese tiempo de vida del producto");
                String area=JOptionPane.showInputDialog("Ingrese el area de la casa donde se usa");
                String instrucciones=JOptionPane.showInputDialog("Ingrese las instrucciones de uso");
                String Fechas=JOptionPane.showInputDialog("Ingrese una fecha en este formato yyyy/MM/dd");
                
                Date fecha=formato.parse(Fechas);
              
                int pos = Integer.parseInt(JOptionPane.showInputDialog("Ingrese posicion de la persona dueña del objeto"));
                lista.get(pos).getLista().add(new Objetos_hogar( tiempo,  area,  instrucciones,  fecha,  color,  descripcion,  marca,  tam,  calidad,  precio,  lista.get(pos).getNombre(), tipo));
                System.out.println(lista);
            } catch (ParseException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        tf_color.setText("");
        ta_descripcion.setText("");
        tf_marca.setText("");
        tf_tam.setText("");
        tf_precio.setText("");

    }//GEN-LAST:event_b_agregarobjetoMouseClicked

    private void b_eliminarobjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_eliminarobjetosMouseClicked
        System.out.println(lista);
        int pos=Integer.parseInt(JOptionPane.showInputDialog("Ingrese posicion de la persona dueña del objeto que desea eliminar"));
        int pos2=Integer.parseInt(JOptionPane.showInputDialog("Ingrese posicion del objeto que desea eliminar"));
        System.out.println("");
        lista.get(pos).getLista().remove(pos2);
        System.out.println(lista);
    }//GEN-LAST:event_b_eliminarobjetosMouseClicked

    private void b_modificaroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_modificaroMouseClicked
        System.out.println(lista);
        int pos=Integer.parseInt(JOptionPane.showInputDialog("Ingrese posicion de la persona dueña del objeto que desea modificar"));
        int pos2=Integer.parseInt(JOptionPane.showInputDialog("Ingrese posicion del objeto que desea modificar"));
        int opc = Integer.parseInt(JOptionPane.showInputDialog("1.modificar color\n" + "2.modificar descripcion\n" + "3.modificar marca\n"+"4.modificar tamaño\n"+"5.modificar precio\n" + "Ingrese numero de lo que desea modificar"));
        if(opc==1){
            String n_color=JOptionPane.showInputDialog("Ingrese nuevo color");
            ((Objeto)lista.get(pos).getLista().get(pos2)).setColor(n_color);
        }
        if(opc==2){
            String n_descripcion=JOptionPane.showInputDialog("Ingrese nueva descripcion");
            ((Objeto)lista.get(pos).getLista().get(pos2)).setDescripcion(n_descripcion);
        }
        if(opc==3){
            String n_marca=JOptionPane.showInputDialog("Ingrese nueva marca");
            ((Objeto)lista.get(pos).getLista().get(pos2)).setMarca(n_marca);
        }
        if(opc==4){
           String n_tam=JOptionPane.showInputDialog("Ingrese nuevo tamaño");
            ((Objeto)lista.get(pos).getLista().get(pos2)).setTam(n_tam); 
        }
        if(opc==5){
            double n_precio=Double.parseDouble(JOptionPane.showInputDialog("Ingrese nuevo precio"));
            ((Objeto)lista.get(pos).getLista().get(pos2)).setPrecio(n_precio);
        }
        System.out.println("");
        System.out.println(lista);
    }//GEN-LAST:event_b_modificaroMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        tabla1.setModel(new javax.swing.table.DefaultTableModel(
                new String[][]{},
                new String[]{
                     lista.toString()
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        

    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_agregar;
    private javax.swing.JButton b_agregarobjeto;
    private javax.swing.JButton b_agregarp;
    private javax.swing.JButton b_eliminar;
    private javax.swing.JButton b_eliminarobjetos;
    private javax.swing.JButton b_eliminarp;
    private javax.swing.JButton b_modificar;
    private javax.swing.JButton b_modificaro;
    private javax.swing.JButton b_modificarp;
    private javax.swing.ButtonGroup bg_calidad;
    private javax.swing.ButtonGroup bg_estado;
    private javax.swing.ButtonGroup bg_rol;
    private javax.swing.ButtonGroup bg_sexos;
    private javax.swing.ButtonGroup bg_tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    private javax.swing.JRadioButton rb7;
    private javax.swing.JRadioButton rb8;
    private javax.swing.JRadioButton rb9;
    private javax.swing.JRadioButton rb_1;
    private javax.swing.JRadioButton rb_casado;
    private javax.swing.JRadioButton rb_casadop;
    private javax.swing.JRadioButton rb_esposo;
    private javax.swing.JRadioButton rb_f;
    private javax.swing.JRadioButton rb_fp;
    private javax.swing.JRadioButton rb_hermana;
    private javax.swing.JRadioButton rb_hermano;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JRadioButton rb_madre;
    private javax.swing.JRadioButton rb_mp;
    private javax.swing.JRadioButton rb_objetos;
    private javax.swing.JRadioButton rb_otro;
    private javax.swing.JRadioButton rb_otrop;
    private javax.swing.JRadioButton rb_padre;
    private javax.swing.JRadioButton rb_ropa;
    private javax.swing.JRadioButton rb_soltero;
    private javax.swing.JRadioButton rb_solterop;
    private javax.swing.JRadioButton rb_zapatos;
    private javax.swing.JSpinner spinner_edad;
    private javax.swing.JSpinner spinner_edadp;
    private javax.swing.JTextArea ta_descripcion;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField tf_altura;
    private javax.swing.JTextField tf_color;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_contraf;
    private javax.swing.JTextField tf_contrap;
    private javax.swing.JTextField tf_horario;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_idp;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombrep;
    private javax.swing.JTextField tf_ocupacion;
    private javax.swing.JTextField tf_peso;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_sueldo;
    private javax.swing.JTextField tf_tam;
    private javax.swing.JTextField tf_tiempo;
    private javax.swing.JTextField tf_trabajo;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
}
